-- MySQL Script generated by MySQL Workbench
-- 04/26/17 10:25:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema medicalThyroid
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `medicalThyroid` ;

-- -----------------------------------------------------
-- Schema medicalThyroid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medicalThyroid` DEFAULT CHARACTER SET utf8 ;
USE `medicalThyroid` ;

-- -----------------------------------------------------
-- Table `medicalThyroid`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicalThyroid`.`patient` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `identifier` JSON NOT NULL,
  `name` JSON NOT NULL,
  `telecom` JSON NOT NULL,
  `gender` TINYTEXT NOT NULL,
  `birthDate` TINYTEXT NOT NULL,
  `address` JSON NOT NULL,
  `maritalStatus` JSON NOT NULL,
  `contact` JSON NOT NULL,
  `communication` JSON NOT NULL,
  `managingOrganization` LONGTEXT NOT NULL,
  `bloodType` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medicalThyroid`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicalThyroid`.`personal` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `identifier` JSON NOT NULL,
  `name` JSON NOT NULL,
  `telecom` JSON NOT NULL,
  `address` JSON NULL DEFAULT NULL,
  `gender` TINYTEXT NOT NULL,
  `birthDate` TINYTEXT NOT NULL,
  `practitionerRole` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `medicalThyroid`.`personal` (`id` ASC);


-- -----------------------------------------------------
-- Table `medicalThyroid`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicalThyroid`.`admin` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `ndi` VARCHAR(45) NOT NULL,
  `ndivalue` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `medicalThyroid`.`admin` (`id` ASC);


-- -----------------------------------------------------
-- Table `medicalThyroid`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicalThyroid`.`users` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicalThyroid`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicalThyroid`.`user_roles` (
  `user_roles_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_roles_id`),
  CONSTRAINT `fk_user_roles_users`
    FOREIGN KEY (`username`)
    REFERENCES `medicalThyroid`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_username_idx` ON `medicalThyroid`.`user_roles` (`username` ASC);

CREATE UNIQUE INDEX `uni_username_role` ON `medicalThyroid`.`user_roles` (`role` ASC, `username` ASC);


-- -----------------------------------------------------
-- Table `medicalThyroid`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicalThyroid`.`exam` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` JSON NOT NULL,
  `subject` JSON NOT NULL,
  `referenceRange` JSON NULL,
  `interpretation` JSON NULL,
  `valueQuantity` JSON NULL,
  `comments` TEXT NULL,
  `issued` TEXT NOT NULL,
  `entity` VARCHAR(45) NOT NULL,
  `performer` JSON NOT NULL,
  `done` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicalThyroid`.`lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicalThyroid`.`lab` (
  `id` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `ndi` VARCHAR(45) NOT NULL,
  `ndivalue` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `entitylab` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `medicalThyroid`.`lab` (`id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO users(username,password,enabled) VALUES ('root','0000', true);
INSERT INTO user_roles (username, role) VALUES ('root', 'ROLE_TEMPORAL');
